// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxM2UE44aTm4jX3br-cfw-Vqikcnagf6w',
    appId: '1:958023250920:web:2ea8a24e450a3cc108aa5d',
    messagingSenderId: '958023250920',
    projectId: 'fgadea-dev',
    authDomain: 'fgadea-dev.firebaseapp.com',
    storageBucket: 'fgadea-dev.appspot.com',
    measurementId: 'G-BB37W4DDDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDN5yKc628iOO9w9CfHBsmV8xGWUNY85E',
    appId: '1:958023250920:android:173d50cc4ab63fcb08aa5d',
    messagingSenderId: '958023250920',
    projectId: 'fgadea-dev',
    storageBucket: 'fgadea-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRspjolYeK0xiTv1NE4D5j61jDp3ozFYI',
    appId: '1:958023250920:ios:b8f14c59c0deb0c908aa5d',
    messagingSenderId: '958023250920',
    projectId: 'fgadea-dev',
    storageBucket: 'fgadea-dev.appspot.com',
    iosClientId:
        '958023250920-ivub9ceqo07q8gs7vlorjo84a8stde25.apps.googleusercontent.com',
    iosBundleId: 'com.example.fgadeaDev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRspjolYeK0xiTv1NE4D5j61jDp3ozFYI',
    appId: '1:958023250920:ios:b8f14c59c0deb0c908aa5d',
    messagingSenderId: '958023250920',
    projectId: 'fgadea-dev',
    storageBucket: 'fgadea-dev.appspot.com',
    iosClientId:
        '958023250920-ivub9ceqo07q8gs7vlorjo84a8stde25.apps.googleusercontent.com',
    iosBundleId: 'com.example.fgadeaDev',
  );
}
